metadata/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Rich_text_Area_check__c</fullName>
        <label>Rich text Area check</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SLASerialNumber__c</fullName>
        <label>SLA Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata/unpackaged/classes/Sample.cls
public class Sample
{
    public String tabOpt {get;set;}
    public String amount {get;set;}
    public Boolean curencyBool {get;set;}
    public string hellorich{get;set;}
    public string entereddata{get;set;}
    public account acc{get;set;}
    public sample()
    {          curencyBool =true; 
                acc= new account();
    }     
   
    public void switch()
    {      curencyBool =false; 
        tabOpt = 'one';
    }
    public pagereference  saveValue(){
        
        acc.Rich_text_Area_check__c=hellorich;
        acc.SLASerialNumber__c=entereddata;
        
        insert acc;
        pagereference pr= new pageReference('/'+acc.id);
        return pr;
    
    }
}