metadata/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Color__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Blue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corain</fullName>
                </value>
                <value>
                    <fullName>Zodiac</fullName>
                </value>
                <value>
                    <fullName>Granite</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/unpackaged/classes/ctrlsajaytestmultiadd.cls
public class ctrlsajaytestmultiadd {

    public ctrlsajaytestmultiadd() {
products1= new List<innerClass>();
    }

List<Product2> products;
public list<innerclass> products1{get;set;}
public ctrlsajaytestmultiadd(ApexPages.StandardController ctlr)
    {
    
        
        
        
    }
    public List<Product2> getProducts() {

        if(Products== null) 
        Products= [select name,Color__c,Application__c,Product__C from Product2 where color__C != NULL];

        return Products;

    }

public class innerclass{
public product2 prod{get;set;}
public innerclass(){
prod= new product2();
}
}
}